-- 권한 관리 테이블
CREATE TABLE `AUTHORITIES` (
    `AUTHORITY_CODE`   VARCHAR(50)   NOT NULL,
    `AUTHORITY_NAME`   VARCHAR(100)  NOT NULL,
    `DESCRIPTION`      VARCHAR(255),
    `USE_YN`           CHAR(1)       DEFAULT 'Y',
    `USE_START_DATE`   DATE,
    `USE_END_DATE`     DATE,
    `CREATED_DATE`     DATETIME      DEFAULT CURRENT_TIMESTAMP,
    `CREATED_ID`       VARCHAR(50),
    `MODIFIED_DATE`    DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `MODIFIED_ID`      VARCHAR(50),
    PRIMARY KEY (`AUTHORITY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `AUTHORITIES` COMMENT = '권한';

ALTER TABLE `AUTHORITIES`
    MODIFY COLUMN `AUTHORITY_CODE` VARCHAR(50) NOT NULL COMMENT '권한 코드',
    MODIFY COLUMN `AUTHORITY_NAME` VARCHAR(100) NOT NULL COMMENT '권한 이름',
    MODIFY COLUMN `DESCRIPTION` VARCHAR(255) COMMENT '권한 설명',
    MODIFY COLUMN `USE_YN` CHAR(1) DEFAULT 'Y' COMMENT '사용 여부',
    MODIFY COLUMN `USE_START_DATE` DATE COMMENT '사용 시작일',
    MODIFY COLUMN `USE_END_DATE` DATE COMMENT '사용 종료일',
    MODIFY COLUMN `CREATED_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    MODIFY COLUMN `CREATED_ID` VARCHAR(50) COMMENT '생성자 ID',
    MODIFY COLUMN `MODIFIED_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    MODIFY COLUMN `MODIFIED_ID` VARCHAR(50) COMMENT '수정자 ID';

-- 공통코드그룹 테이블
CREATE TABLE `CODE_GROUPS` (
    `GROUP_CODE`        VARCHAR(50)   NOT NULL,
    `GROUP_NAME`        VARCHAR(100)  NOT NULL,
    `GROUP_EXPLANATION` VARCHAR(255),
    `USE_YN`            CHAR(1)       DEFAULT 'Y',
    `USE_START_DATE`    DATE,
    `USE_END_DATE`      DATE,
    `VERSION`           INT           DEFAULT 0,
    `CREATED_DATE`      DATETIME      DEFAULT CURRENT_TIMESTAMP,
    `CREATED_ID`        VARCHAR(50),
    `MODIFIED_DATE`     DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `MODIFIED_ID`       VARCHAR(50),
    PRIMARY KEY (`GROUP_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `CODE_GROUPS` COMMENT = '공통코드그룹';

ALTER TABLE `CODE_GROUPS`
    MODIFY COLUMN `GROUP_CODE` VARCHAR(50) NOT NULL COMMENT '그룹 코드',
    MODIFY COLUMN `GROUP_NAME` VARCHAR(100) NOT NULL COMMENT '그룹 이름',
    MODIFY COLUMN `GROUP_EXPLANATION` VARCHAR(255) COMMENT '그룹 설명',
    MODIFY COLUMN `USE_YN` CHAR(1) DEFAULT 'Y' COMMENT '사용 여부',
    MODIFY COLUMN `USE_START_DATE` DATE COMMENT '사용 시작일',
    MODIFY COLUMN `USE_END_DATE` DATE COMMENT '사용 종료일',
    MODIFY COLUMN `VERSION` INT DEFAULT 0 COMMENT '버전',
    MODIFY COLUMN `CREATED_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    MODIFY COLUMN `CREATED_ID` VARCHAR(50) COMMENT '생성자 ID',
    MODIFY COLUMN `MODIFIED_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    MODIFY COLUMN `MODIFIED_ID` VARCHAR(50) COMMENT '수정자 ID';

-- 공통코드 상세 테이블
CREATE TABLE `CODES` (
    `GROUP_CODE`       VARCHAR(50)   NOT NULL,
    `CODE`             VARCHAR(50)   NOT NULL,
    `CODE_NAME`        VARCHAR(100)  NOT NULL,
    `CODE_EXPLANATION` VARCHAR(255),
    `USE_YN`           CHAR(1)       DEFAULT 'Y',
    `USE_START_DATE`   DATE,
    `USE_END_DATE`     DATE,
    `VERSION`          INT           DEFAULT 0,
    `CREATED_DATE`     DATETIME      DEFAULT CURRENT_TIMESTAMP,
    `CREATED_ID`       VARCHAR(50),
    `MODIFIED_DATE`    DATETIME      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `MODIFIED_ID`      VARCHAR(50),
    PRIMARY KEY (`GROUP_CODE`, `CODE`),
    CONSTRAINT `FK_CODES_GROUP` FOREIGN KEY (`GROUP_CODE`) REFERENCES `CODE_GROUPS` (`GROUP_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `CODES` COMMENT = '공통코드 상세';

ALTER TABLE `CODES`
    MODIFY COLUMN `GROUP_CODE` VARCHAR(50) NOT NULL COMMENT '그룹 코드',
    MODIFY COLUMN `CODE` VARCHAR(50) NOT NULL COMMENT '코드',
    MODIFY COLUMN `CODE_NAME` VARCHAR(100) NOT NULL COMMENT '코드 이름',
    MODIFY COLUMN `CODE_EXPLANATION` VARCHAR(255) COMMENT '코드 설명',
    MODIFY COLUMN `USE_YN` CHAR(1) DEFAULT 'Y' COMMENT '사용 여부',
    MODIFY COLUMN `USE_START_DATE` DATE COMMENT '사용 시작일',
    MODIFY COLUMN `USE_END_DATE` DATE COMMENT '사용 종료일',
    MODIFY COLUMN `VERSION` INT DEFAULT 0 COMMENT '버전',
    MODIFY COLUMN `CREATED_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    MODIFY COLUMN `CREATED_ID` VARCHAR(50) COMMENT '생성자 ID',
    MODIFY COLUMN `MODIFIED_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정 일시',
    MODIFY COLUMN `MODIFIED_ID` VARCHAR(50) COMMENT '수정자 ID';

-- 권한 데이터 생성
INSERT INTO `AUTHORITIES` (
    `AUTHORITY_CODE`, `AUTHORITY_NAME`, `DESCRIPTION`, `USE_YN`, `USE_START_DATE`, `USE_END_DATE`, `CREATED_DATE`, `CREATED_ID`, `MODIFIED_DATE`, `MODIFIED_ID`
) VALUES
('ROLE_ADMIN', '관리자', '관리자 권한', 'Y', '1900-01-01', '9999-12-31', NOW(), 'System', NOW(), 'System'),
('ROLE_MANAGER', '매니저', '관리자 대행 권한', 'Y', '1900-01-01', '9999-12-31', NOW(), 'System', NOW(), 'System'),
('ROLE_DB_ENGINEER', 'DB 엔지니어', 'DB 엔지니어 권한', 'Y', '1900-01-01', '9999-12-31', NOW(), 'System', NOW(), 'System'),
('ROLE_GUEST', '게스트', '초기 사용자 권한', 'Y', '1900-01-01', '9999-12-31', NOW(), 'System', NOW(), 'System');

-- 공통코드그룹 데이터 생성
INSERT INTO `CODE_GROUPS` (
    `GROUP_CODE`, `GROUP_NAME`, `GROUP_EXPLANATION`, `USE_YN`, `USE_START_DATE`, `USE_END_DATE`, `VERSION`, `CREATED_DATE`, `CREATED_ID`, `MODIFIED_DATE`, `MODIFIED_ID`
) VALUES
('COMMON_CODE_01', '공통코드_01', '공통코드_01 설명', 'Y', '1900-01-01', '9999-12-31', 0, NOW(), 'System', NOW(), 'System'),
('COMMON_CODE_02', '공통코드_02', '공통코드_02 설명', 'Y', '1900-01-01', '9999-12-31', 0, NOW(), 'System', NOW(), 'System'),
('COMMON_CODE_03', '공통코드_03', '공통코드_03 설명', 'Y', '1900-01-01', '9999-12-31', 0, NOW(), 'System', NOW(), 'System');

-- 공통코드 데이터 생성
INSERT INTO `CODES` (
    `GROUP_CODE`, `CODE`, `CODE_NAME`, `CODE_EXPLANATION`, `USE_YN`, `USE_START_DATE`, `USE_END_DATE`, `VERSION`, `CREATED_DATE`, `CREATED_ID`, `MODIFIED_DATE`, `MODIFIED_ID`
) VALUES
('COMMON_CODE_01', 'CODE_01', '코드_01', '코드_01 설명', 'Y', '1900-01-01', '9999-12-31', 0, NOW(), 'System', NOW(), 'System'),
('COMMON_CODE_01', 'CODE_02', '코드_02', '코드_02 설명', 'Y', '1900-01-01', '9999-12-31', 0, NOW(), 'System', NOW(), 'System'),
('COMMON_CODE_01', 'CODE_03', '코드_03', '코드_03 설명', 'Y', '1900-01-01', '9999-12-31', 0, NOW(), 'System', NOW(), 'System');