-- 권한 관리 테이블
CREATE TABLE "AUTHORITIES" (
    "AUTHORITY_CODE"   VARCHAR(50)   NOT NULL,
    "AUTHORITY_NAME"   VARCHAR(100)  NOT NULL,
    "DESCRIPTION"      VARCHAR(255),
    "USE_YN"           CHAR(1)       DEFAULT 'Y',
    "USE_START_DATE"   DATE,
    "USE_END_DATE"     DATE,
    "CREATED_DATE"     TIMESTAMP     DEFAULT NOW(),
    "CREATED_ID"       VARCHAR(50),
    "MODIFIED_DATE"    TIMESTAMP     DEFAULT NOW(),
    "MODIFIED_ID"      VARCHAR(50),
    CONSTRAINT "PK_AUTHORITIES" PRIMARY KEY ("AUTHORITY_CODE")
);

COMMENT ON TABLE "AUTHORITIES" IS '권한';
COMMENT ON COLUMN "AUTHORITIES"."AUTHORITY_CODE" IS '권한 코드';
COMMENT ON COLUMN "AUTHORITIES"."AUTHORITY_NAME" IS '권한 이름';
COMMENT ON COLUMN "AUTHORITIES"."DESCRIPTION" IS '권한 설명';
COMMENT ON COLUMN "AUTHORITIES"."USE_YN" IS '사용 여부';
COMMENT ON COLUMN "AUTHORITIES"."USE_START_DATE" IS '사용 시작일';
COMMENT ON COLUMN "AUTHORITIES"."USE_END_DATE" IS '사용 종료일';
COMMENT ON COLUMN "AUTHORITIES"."CREATED_DATE" IS '생성 일시';
COMMENT ON COLUMN "AUTHORITIES"."CREATED_ID" IS '생성자 ID';
COMMENT ON COLUMN "AUTHORITIES"."MODIFIED_DATE" IS '수정 일시';
COMMENT ON COLUMN "AUTHORITIES"."MODIFIED_ID" IS '수정자 ID';

-- 공통코드그룹 테이블
CREATE TABLE "CODE_GROUPS" (
    "GROUP_CODE"       VARCHAR(50)   NOT NULL,
    "GROUP_NAME"       VARCHAR(100)  NOT NULL,
    "GROUP_EXPLANATION" VARCHAR(255),
    "USE_YN"           CHAR(1)       DEFAULT 'Y',
    "USE_START_DATE"   DATE,
    "USE_END_DATE"     DATE,
    "VERSION"          INTEGER       DEFAULT 0,
    "CREATED_DATE"     TIMESTAMP     DEFAULT NOW(),
    "CREATED_ID"       VARCHAR(50),
    "MODIFIED_DATE"    TIMESTAMP     DEFAULT NOW(),
    "MODIFIED_ID"      VARCHAR(50),
    CONSTRAINT "PK_CODE_GROUPS" PRIMARY KEY ("GROUP_CODE")
);

COMMENT ON TABLE "CODE_GROUPS" IS '공통코드그룹';
COMMENT ON COLUMN "CODE_GROUPS"."GROUP_CODE" IS '그룹 코드';
COMMENT ON COLUMN "CODE_GROUPS"."GROUP_NAME" IS '그룹 이름';
COMMENT ON COLUMN "CODE_GROUPS"."GROUP_EXPLANATION" IS '그룹 설명';
COMMENT ON COLUMN "CODE_GROUPS"."USE_YN" IS '사용 여부';
COMMENT ON COLUMN "CODE_GROUPS"."USE_START_DATE" IS '사용 시작일';
COMMENT ON COLUMN "CODE_GROUPS"."USE_END_DATE" IS '사용 종료일';
COMMENT ON COLUMN "CODE_GROUPS"."VERSION" IS '버전';
COMMENT ON COLUMN "CODE_GROUPS"."CREATED_DATE" IS '생성 일시';
COMMENT ON COLUMN "CODE_GROUPS"."CREATED_ID" IS '생성자 ID';
COMMENT ON COLUMN "CODE_GROUPS"."MODIFIED_DATE" IS '수정 일시';
COMMENT ON COLUMN "CODE_GROUPS"."MODIFIED_ID" IS '수정자 ID';

-- 공통코드 상세 테이블
CREATE TABLE "CODES" (
    "GROUP_CODE"       VARCHAR(50)   NOT NULL,
    "CODE"             VARCHAR(50)   NOT NULL,
    "CODE_NAME"        VARCHAR(100)  NOT NULL,
    "CODE_EXPLANATION" VARCHAR(255),
    "USE_YN"           CHAR(1)       DEFAULT 'Y',
    "USE_START_DATE"   DATE,
    "USE_END_DATE"     DATE,
    "VERSION"          INTEGER       DEFAULT 0,
    "CREATED_DATE"     TIMESTAMP     DEFAULT NOW(),
    "CREATED_ID"       VARCHAR(50),
    "MODIFIED_DATE"    TIMESTAMP     DEFAULT NOW(),
    "MODIFIED_ID"      VARCHAR(50),
    CONSTRAINT "PK_CODES" PRIMARY KEY ("GROUP_CODE", "CODE"),
    CONSTRAINT "FK_CODES_GROUP" FOREIGN KEY ("GROUP_CODE") REFERENCES "CODE_GROUPS"("GROUP_CODE")
);

COMMENT ON TABLE "CODES" IS '공통코드상세';
COMMENT ON COLUMN "CODES"."GROUP_CODE" IS '그룹 코드';
COMMENT ON COLUMN "CODES"."CODE" IS '코드';
COMMENT ON COLUMN "CODES"."CODE_NAME" IS '코드 이름';
COMMENT ON COLUMN "CODES"."CODE_EXPLANATION" IS '코드 설명';
COMMENT ON COLUMN "CODES"."USE_YN" IS '사용 여부';
COMMENT ON COLUMN "CODES"."USE_START_DATE" IS '사용 시작일';
COMMENT ON COLUMN "CODES"."USE_END_DATE" IS '사용 종료일';
COMMENT ON COLUMN "CODES"."VERSION" IS '버전';
COMMENT ON COLUMN "CODES"."CREATED_DATE" IS '생성 일시';
COMMENT ON COLUMN "CODES"."CREATED_ID" IS '생성자 ID';
COMMENT ON COLUMN "CODES"."MODIFIED_DATE" IS '수정 일시';
COMMENT ON COLUMN "CODES"."MODIFIED_ID" IS '수정자 ID';

-- 권한 데이터 생성

INSERT INTO "AUTHORITIES" (
      "CREATED_DATE"
    , "CREATED_ID"
    , "MODIFIED_DATE"
    , "MODIFIED_ID"
    , "AUTHORITY_CODE"
    , "AUTHORITY_NAME"
    , "DESCRIPTION"
    , "USE_YN"
    , "USE_START_DATE"
    , "USE_END_DATE"
) VALUES (NOW(), 'System', NOW(), 'System', 'ROLE_ADMIN', '관리자', '관리자 권한', 'Y', TO_DATE('19000101', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'))
       , (NOW(), 'System', NOW(), 'System', 'ROLE_MANAGER', '매니저', '관리자 대행 권한', 'Y', TO_DATE('19000101', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'))
       , (NOW(), 'System', NOW(), 'System', 'ROLE_DB_ENGINEER', 'DB 엔지니어', 'DB 엔지니어 권한', 'Y', TO_DATE('19000101', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'))
       , (NOW(), 'System', NOW(), 'System', 'ROLE_GUEST', '게스트', '초기 사용자 권한', 'Y', TO_DATE('19000101', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'))
       ;

-- 공통코드그룹 데이터 생성

INSERT INTO "CODE_GROUPS" (
      "CREATED_DATE"
    , "CREATED_ID"
    , "MODIFIED_DATE"
    , "MODIFIED_ID"
    , "GROUP_CODE"
    , "GROUP_NAME"
    , "GROUP_EXPLANATION"
    , "USE_YN"
    , "USE_START_DATE"
    , "USE_END_DATE"
    , "VERSION"
) VALUES (NOW(), 'System', NOW(), 'System', 'COMMON_CODE_01', '공통코드_01', '공통코드_01 설명', 'Y', TO_DATE('19000101', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 0)
       , (NOW(), 'System', NOW(), 'System', 'COMMON_CODE_02', '공통코드_02', '공통코드_02 설명', 'Y', TO_DATE('19000101', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 0)
       , (NOW(), 'System', NOW(), 'System', 'COMMON_CODE_03', '공통코드_03', '공통코드_03 설명', 'Y', TO_DATE('19000101', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 0)
       ;

-- 공통코드 데이터 생성

INSERT INTO "CODES" (
      "GROUP_CODE"
    , "CREATED_DATE"
    , "CREATED_ID"
    , "MODIFIED_DATE"
    , "MODIFIED_ID"
    , "CODE"
    , "CODE_NAME"
    , "CODE_EXPLANATION"
    , "USE_YN"
    , "USE_START_DATE"
    , "USE_END_DATE"
    , "VERSION"
) VALUES ('COMMON_CODE_01', NOW(), 'System', NOW(), 'System', 'CODE_01', '코드_01', '코드_01 설명', 'Y', TO_DATE('19000101', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 0)
       , ('COMMON_CODE_01', NOW(), 'System', NOW(), 'System', 'CODE_02', '코드_02', '코드_02 설명', 'Y', TO_DATE('19000101', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 0)
       , ('COMMON_CODE_01', NOW(), 'System', NOW(), 'System', 'CODE_03', '코드_03', '코드_03 설명', 'Y', TO_DATE('19000101', 'YYYYMMDD'), TO_DATE('99991231', 'YYYYMMDD'), 0)
       ;
